### ISSUE TITLE
Using contacts API endpoint instead of users

### ISSUE THREAD

**Issue by superalex** [tagip/forest-guard#1]
This app looks great, thank you very much for sharing ;)

I've seen the users endpoint is used, if the Taiga instance used is public then the results are not very useful, I would like to see only the users who I am working with. Those users can be filtered (being memberships of projects where I am a member too) using the contacts API: https://taigaio.github.io/taiga-doc/dist/api.html#users-get-contacts

**Comment by mikaoelitiana** [comment]
Thanks for this. I will work on implementing this.

**Comment by superalex** [comment]
![image](https://cloud.githubusercontent.com/assets/1579633/26584055/c69cd7f4-4547-11e7-8430-a260dcb57f30.png)
