### ISSUE TITLE
Add watchers to Issue and Tasks

### ISSUE THREAD

**Issue by Sirhexalot** [tagip/forest-guard#13]
Hi,

would it be possible to expand the filter to have also the watchers:

` <List {...props} perPage={30} filter={{ status__is_closed: false, assigned_to: localStorage.getItem('user_id') }}>`

**Comment by mikaoelitiana** [comment]
I think it will not be possible in the same list because the filters are combined with `AND` but not `OR` so the query would not work correctly.
