### ISSUE TITLE
Users Overview

### ISSUE THREAD

**Issue by Sirhexalot** [tagip/forest-guard#14]
Is it possible to have the field this.props.record.project_extra_info.name in the users overview?

It would be great if it is poosible to have a view which is group by this.props.record.project_extra_info.name

Best
Adrian

**Comment by mikaoelitiana** [comment]
You are right, I will add that

**Comment by mikaoelitiana** [comment]
It would be something like this : 

<img width="1060" alt="capture d ecran 2017-09-05 a 10 57 48" src="https://user-images.githubusercontent.com/674667/30050985-0b4f6b4a-9229-11e7-9ed2-8804c00af628.png">

**Comment by Sirhexalot** [comment]
Pefect – Great!

 

Von: Mika Andrianarijaona [mailto:notifications@github.com] 
Gesendet: Dienstag, 5. September 2017 09:58
An: tagip/forest-guard <forest-guard@noreply.github.com>
Cc: Sirhexalot <adrian@schmolzi-online.de>; Author <author@noreply.github.com>
Betreff: Re: [tagip/forest-guard] Users Overview (#14)

 

It would be something like this :

 <https://user-images.githubusercontent.com/674667/30050985-0b4f6b4a-9229-11e7-9ed2-8804c00af628.png>
