### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by Sirhexalot** [tagip/forest-guard#16]
Would it be possible to have a personal user dashboard?

> List of my projects
>> List of my issues
>> List of my tasks

We want to use taiga as a multi project management solution. But the taiga dashboard is not very usefull for us. 

Your project is absolut fantastic! If you like we can also help on adding new features.

**Comment by mikaoelitiana** [comment]
I will be really glad to have help @Sirhexalot ! I will check how we can create a dashboard here

**Comment by mikaoelitiana** [comment]
@Sirhexalot can you try this on branch `fix-16` and tell me what you think of it? It looks like this: 

<img width="1912" alt="capture d ecran 2017-09-20 a 17 08 10" src="https://user-images.githubusercontent.com/674667/30648796-8befce02-9e27-11e7-87d3-93f96c7bc610.png">

So on the dashboard, the user will see all his projects, his assigned tasks and all unassigned tasks.

**Comment by Sirhexalot** [comment]
Great!!!!!!!!!! Wonderull!!! 

I did some minor improvements. I would suggest to devide my_issues and my_tasks. 

Please take a look ;-)

[src.zip](https://github.com/tagip/forest-guard/files/1320262/src.zip)

**Comment by mikaoelitiana** [comment]
OK, maybe you can create a branch for that so I can quickly check it?

**Comment by Sirhexalot** [comment]
Sorry - i do now know how... Can you tell me?

**Comment by mikaoelitiana** [comment]
Oh you need to have your own fork  of the project for that. For now I will check from the file you provided

**Comment by Sirhexalot** [comment]
https://github.com/Sirhexalot/forest-guard ??

Does that help?

**Comment by mikaoelitiana** [comment]
Yes that's exactly it, now inside your repository, you can switch to branch fix-16 and edit files directly through github interface. Finally, you can create a pull request from there and I will be able to test it

**Comment by Sirhexalot** [comment]
Is it possible to have a reload of the dashboard every 30 seconds or to do the call again without a reload
