### ISSUE TITLE
Integration in Taiga possible?

### ISSUE THREAD

**Issue by Sirhexalot** [tagip/forest-guard#19]
https://github.com/juanfran/taiga-override-directive-example

**Comment by mikaoelitiana** [comment]
It's quite complicated to implement and I don't think it will make more value inside taiga. They may add something similar to this.

**Comment by Sirhexalot** [comment]
Hi, we wrote a new module in taiga-front. So will switch to that solution. Would you like to join?

**Comment by mikaoelitiana** [comment]
Yes I would love to help
