### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Sirhexalot** [tagip/forest-guard#7]
Hi there,

I would like to provide a german translation. How can I help?

**Comment by mikaoelitiana** [comment]
Hello @Sirhexalot. Thanks for letting us know you are willing to help. There are 2 options for this:

1. You can edit the `src/i18n.js` file to add a new translation. This file will need some refactor later when more translations are provided.

2. You can also send us the translation and we will add them. Here are the base english version : 

```
en: {
    fg: {
      created_on: 'Created on',
      due_date: 'Due date',
      work_in_progress: 'Work in progress',
    },
    resources: {
      users: {
        name: 'Work in progress',
        fields: {
          full_name: 'Name',
          tasks_issues: 'Tasks/Issues',
        }
      }
    }
  }
```

Best!

**Comment by Sirhexalot** [comment]
Hi,

 

here comes the translation.

 

moment.locale('de', {

  months: 'Jaunar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember'.split('_'),

  monthsShort: 'Jan._Feb._März_Apr._Mai_Juni_Juli_Aug._Sept._Okt._Nov._Dez.'.split('_'),

  monthsParseExact: true,

  weekdays: 'Sonntag_Montag_Dientag_Mittwoch_Donnerstag_Freitag_Samstag'.split('_'),

  weekdaysShort: 'So._Mo._Di._Mi._Do._Fr._Sa.'.split('_'),

  weekdaysMin: 'So_Mo_Di_Mi_Do_Fr_Sa'.split('_'),

  weekdaysParseExact: true,

  longDateFormat: {

    LT: 'HH:mm',

    LTS: 'HH:mm:ss',

    L: 'DD/MM/YYYY',

    LL: 'D MMMM YYYY',

    LLL: 'D MMMM YYYY HH:mm',

    LLLL: 'dddd D MMMM YYYY HH:mm'

  },

  calendar: {

                sameDay: '[heute um}] LT',

    nextDay: '[morgen um] LT',

    nextWeek: 'dddd [in] LT',

    lastDay: '[Gestern um] LT',

    lastWeek: 'dddd [vor dem] LT',

    sameElse: 'L'

  },

  relativeTime: {

    future: 'in %s',

    past: 'vor %s',

    s: 'einigen Sekunden',

    m: 'eine Minute',

    mm: '%d Minuten',

    h: 'eine Stunde',

    hh: '%d Stunden',

    d: 'eine Woche',

    dd: '%d Wochen',

    M: 'ein Monat',

    MM: '%d Monate',

    y: 'ein Jahr',

    yy: '%d Jahre'

  },

  dayOfMonthOrdinalParse: /\d{1,2}(er|e)/,

  ordinal: function (number) {

    return number + (number === 1 ? 'er' : 'e');

  },

  meridiemParse: /PD|MD/,

  isPM: function (input) {

    return input.charAt(0) === 'M';

  },

  // In case the meridiem units are not separated around 12, then implement

  // this function (look at locale/id.js for an example).

  // meridiemHour : function (hour, meridiem) {

  //     return /* 0-23 hour, given meridiem token and hour 1-12 */ ;

  // },

  meridiem: function (hours, minutes, isLower) {

    return hours < 12 ? 'PD' : 'MD';

  },

  week: {

    dow: 1, // Monday is the first day of the week.

    doy: 4  // The week that contains Jan 4th is the first week of the year.

  }

});

 

 

Von: Mika Andrianarijaona [mailto:notifications@github.com] 
Gesendet: Freitag, 21. Juli 2017 10:45
An: tagip/forest-guard <forest-guard@noreply.github.com>
Cc: Sirhexalot <adrian@schmolzi-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [tagip/forest-guard] German Translation (#7)

 

Hello @Sirhexalot <https://github.com/sirhexalot> . Thanks for letting us know you are willing to help. There are 2 options for this:

1.	You can edit the src/i18n.js file to add a new translation. This file will need some refactor later when more translations are provided.
2.	You can also send us the translation and we will add them. Here are the base english version :

en: {
    fg: {
      created_on: 'Created on',
      due_date: 'Due date',
      work_in_progress: 'Work in progress',
    },
    resources: {
      users: {
        name: 'Work in progress',
        fields: {
          full_name: 'Name',
          tasks_issues: 'Tasks/Issues',
        }
      }
    }
  }

Best!

**Comment by mikaoelitiana** [comment]
Can you also provide translation for the text in 

```
en: {
    fg: {
      created_on: 'Created on',
      due_date: 'Due date',
      work_in_progress: 'Work in progress',
    },
    resources: {
      users: {
        name: 'Work in progress',
        fields: {
          full_name: 'Name',
          tasks_issues: 'Tasks/Issues',
        }
      }
    }
  }

```

**Comment by Sirhexalot** [comment]
de: {
    fg: {
      created_on: 'Erstellt am',
      due_date: 'Fällig am',
      work_in_progress: 'In Arbeit',
    },
    resources: {
      users: {
        name: 'In Arbeit',
        fields: {
          full_name: 'Name',
          tasks_issues: 'Aufgabe/Problem',
        }
      }
    }
  }
 
Best
Adrian

 

 

Von: Mika Andrianarijaona [mailto:notifications@github.com] 
Gesendet: Freitag, 21. Juli 2017 15:01
An: tagip/forest-guard <forest-guard@noreply.github.com>
Cc: Sirhexalot <adrian@schmolzi-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [tagip/forest-guard] German Translation (#7)

 

Can you also provide translation for the text in

en: {
    fg: {
      created_on: 'Created on',
      due_date: 'Due date',
      work_in_progress: 'Work in progress',
    },
    resources: {
      users: {
        name: 'Work in progress',
        fields: {
          full_name: 'Name',
          tasks_issues: 'Tasks/Issues',
        }
      }
    }
  }

**Comment by mikaoelitiana** [comment]
Thank you @Sirhexalot, I have just added the german localization.
